version: '3.3'

services:
  web:
    build: .
    command: >
      sh -c "gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app/
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - migration
    networks:
      - backend

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ertay
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: shop_db
    container_name: db_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - backend

  migration:
    build: .
    restart: on-failure

    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate"
    volumes:
      - .:/usr/src/app/
    depends_on:
      - db
    networks:
      - backend

  redis:
    image: redis
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A config worker -l INFO
    volumes:
      - .:/usr/src/app/
    depends_on:
      - web
      - redis

  nginx:
     build:
       context: .
       dockerfile: nginx/Dockerfile
     ports:
       - "80:80"
     volumes:
       - static_volume:/usr/src/app/static
       - media_volume:/usr/src/app/media
     depends_on:
       - web


volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  backend: